# Generated by Django 2.1.1 on 2019-01-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, max_length=50, verbose_name='件名')),
                ('description', models.TextField(blank=True, verbose_name='本文')),
                ('date', models.DateField(verbose_name='日付')),
            ],
        ),
    ]
